### ISSUE TITLE
parse slice map to map got wired result

### ISSUE THREAD

**Issue by timestee** [sandwich-go/xconf#6]
```yaml
sm: 
  - foo : bar
  - bar : baz
```

```golang
type Conf struct {
   Result   map[string]string `xconf:"sm"`
}
```

got this result：
```golang 
map[string]string{"bar" : "baz"} 
```

it should be:
```golang
 map[string]string{"foo": "bar", "bar": "baz"}
```
